### ISSUE TITLE
Shadow Simulation does not match with real situation

### ISSUE THREAD

**Issue by lenasophia711** [ni1o1/pybdshadow#17]
Hey!

I'm trying to calculate shadows on the roof of my building. To verify the model, I took various pictures through the day of the shadow on my roof, to compare them with the model output. In general it looks okay, but the shadows from the surrounding buildings are smaller than on my pictures.

To fix the issue, I have already tried various things:
- checked all the coordinates again
- checked the building heights (if I change the building height from the building that throws the shadow from 37 to 55 metres, the shadows from the simulation and my foto match during all times)
- checked the time zone and conversion to UTC, summer and wintertime, and the time of sunrise and sundown
- checked the calculated azimuth and altitude of the sun

Now I'm out of ideas, why the shadow in the simulation and my photo don't match. Do you have any idea what I could try to fix it?

Thank you!

**Comment by ni1o1** [comment]
I have carefully considered it, and there is a possibility. Our algorithm projects the building outline onto the EPSG:3857 coordinate system and then calculates the shadows. However, there can be some deviations in distances under the EPSG:3857 coordinate system projection, which may result in differences between the calculated results and the actual ones.

Based on your experiment, it seems that only the height of the buildings would have an impact, indicating that the issue lies with the distance calculation.

If the projection coordinate system in our algorithm to the local projection coordinate system, the calculation results may be more accurate.

**Comment by ni1o1** [comment]
We recently replaced the Mercator projection in the algorithm with the Equidistant projection. Could you please update to version 0.3.4 of pybdshadow and test whether this issue has been resolved?
